name: camera_windows_example
description: Demonstrates how to use the camera_windows plugin.
publish_to: "none"

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  awesome_snackbar_content: ^0.1.5
  camera_platform_interface: ^2.6.0
  camera_windows: ^0.2.6+1

  flutter:
    sdk: flutter
  flutter_doc_scanner: ^0.0.15
  flutter_ocr_camera: ^0.0.3
  get: ^4.6.6
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  form_validation: ^3.2.0
  image_picker_windows: ^0.2.1+1
  flutter_animate: ^4.5.2
  flutter_ocr_sdk: ^1.2.0
  webview_windows: ^0.4.0

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/