name: camera_windows_example
description: Demonstrates how to use the camera_windows plugin.
publish_to: "none"

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  camera_platform_interface: ^2.6.0
  camera_windows: ^0.2.6+1
  flutter_doc_scanner:
      git:
        url: https://github.com/SarangthemAmarjit/flutter_doc_scanner.git
        ref: main # branch name


  
  flutter:
    sdk: flutter

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
