name: camera_windows_example
description: Demonstrates how to use the camera_windows plugin.
publish_to: "none"

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  awesome_snackbar_content: ^0.1.5
  camera_platform_interface: ^2.6.0
  camera_windows: ^0.2.6+1
  flutter:
    sdk: flutter
  flutter_doc_scanner: ^0.0.15
  get: ^4.6.6
  image_picker: ^1.1.2
  image_picker_windows: ^0.2.1+1
  opencv_dart: ^1.3.3

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
